-- Remove all virtuemart data

DELETE FROM `#__virtuemart_calcs`;
DELETE FROM `#__virtuemart_calc_shoppergroups`;
DELETE FROM `#__virtuemart_calc_countries`;
DELETE FROM `#__virtuemart_calc_states`;
DELETE FROM `#__virtuemart_categories`;
DELETE FROM `#__virtuemart_category_categories`;
DELETE FROM `#__virtuemart_coupons`;
DELETE FROM `#__virtuemart_manufacturers`;
DELETE FROM `#__virtuemart_manufacturercategories`;
DELETE FROM `#__virtuemart_orders`;
DELETE FROM `#__virtuemart_order_histories`;
DELETE FROM `#__virtuemart_order_items`;
DELETE FROM `#__virtuemart_orderstates`;
DELETE FROM `#__virtuemart_order_userinfos`;
DELETE FROM `#__virtuemart_products`;
DELETE FROM `#__virtuemart_product_categories`;
DELETE FROM `#__virtuemart_product_downloads`;
DELETE FROM `#__virtuemart_products_files`;
DELETE FROM `#__virtuemart_product_manufacturers`;
DELETE FROM `#__virtuemart_product_prices`;
DELETE FROM `#__virtuemart_product_producttypes`;
DELETE FROM `#__virtuemart_product_relations`;
DELETE FROM `#__virtuemart_rating_reviews`;
DELETE FROM `#__virtuemart_producttypes`;
DELETE FROM `#__virtuemart_producttype_customfields`;
DELETE FROM `#__virtuemart_vmusers`;
DELETE FROM `#__virtuemart_userinfos`;
DELETE FROM `#__virtuemart_vmuser_shoppergroups`;
DELETE FROM `#__virtuemart_shippingcarriers`;
DELETE FROM `#__virtuemart_shippingrates`;
DELETE FROM `#__virtuemart_shoppergroups`;
DELETE FROM `#__virtuemart_orders`;
DELETE FROM `#__virtuemart_order_histories`;
DELETE FROM `#__virtuemart_order_items`;
DELETE FROM `#__virtuemart_order_userinfos`;
DELETE FROM `#__virtuemart_waitingusers`;
DELETE FROM `#__virtuemart_worldzones`;
ALTER TABLE `#__virtuemart_calcs` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_calc_shoppergroups` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_calc_countries` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_calc_states` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_categories` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_category_categories` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_coupons` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_manufacturers` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_manufacturercategories` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_orders` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_order_histories` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_order_items` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_orderstates` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_order_userinfos` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_products` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_product_categories` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_product_downloads` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_products_files` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_product_manufacturers` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_product_prices` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_product_producttypes` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_product_relations` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_rating_reviews` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_producttypes` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_producttype_customfields` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_vmusers` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_userinfos` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_vmuser_shoppergroups` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_shippingcarriers` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_shippingrates` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_shoppergroups` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_orders` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_order_histories` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_order_items` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_order_userinfos` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_waitingusers` AUTO_INCREMENT = 1;
ALTER TABLE `#__virtuemart_worldzones` AUTO_INCREMENT = 1;