-- Remove all virtuemart data

DELETE FROM `#__vm_calc`;
DELETE FROM `#__vm_category`;
DELETE FROM `#__vm_category_xref`;
DELETE FROM `#__vm_coupons`;
DELETE FROM `#__vm_orders`;
DELETE FROM `#__vm_order_history`;
DELETE FROM `#__vm_order_item`;
DELETE FROM `#__vm_order_payment`;
DELETE FROM `#__vm_order_status`;
DELETE FROM `#__vm_order_user_info`;
DELETE FROM `#__vm_product`;
DELETE FROM `#__vm_product_attribute`;
DELETE FROM `#__vm_product_attribute_sku`;
DELETE FROM `#__vm_product_category_xref`;
DELETE FROM `#__vm_product_discount`;
DELETE FROM `#__vm_product_download`;
DELETE FROM `#__vm_product_files`;
DELETE FROM `#__vm_product_mf_xref`;
DELETE FROM `#__vm_product_price`;
DELETE FROM `#__vm_product_product_type_xref`;
DELETE FROM `#__vm_product_relations`;
DELETE FROM `#__vm_product_reviews`;
DELETE FROM `#__vm_product_type`;
DELETE FROM `#__vm_product_type_parameter`;
DELETE FROM `#__vm_product_votes`;
DELETE FROM `#__vm_tax_rate`;
DELETE FROM `#__vm_waiting_list`;